// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzMDvLQmD9LXrN_TT-HGon7jAyfb2_iok',
    appId: '1:409083412762:web:a785ece1aa6332f087eca3',
    messagingSenderId: '409083412762',
    projectId: 'ecoexpense-1cde6',
    authDomain: 'ecoexpense-1cde6.firebaseapp.com',
    storageBucket: 'ecoexpense-1cde6.appspot.com',
    measurementId: 'G-9GJQCCQ31Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2bVIAxMPsWksVSIM3SMUEi5FAVsB3iw',
    appId: '1:409083412762:android:6f28d8a9153c03b687eca3',
    messagingSenderId: '409083412762',
    projectId: 'ecoexpense-1cde6',
    storageBucket: 'ecoexpense-1cde6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZSMOtfuFbZgCjo4tyY7Oynl4HpdDwSz0',
    appId: '1:409083412762:ios:c526797404b9645187eca3',
    messagingSenderId: '409083412762',
    projectId: 'ecoexpense-1cde6',
    storageBucket: 'ecoexpense-1cde6.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZSMOtfuFbZgCjo4tyY7Oynl4HpdDwSz0',
    appId: '1:409083412762:ios:32ee02483c524f6d87eca3',
    messagingSenderId: '409083412762',
    projectId: 'ecoexpense-1cde6',
    storageBucket: 'ecoexpense-1cde6.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
